// Generated by gencpp from file basic_comms/signal_msgs.msg
// DO NOT EDIT!


#ifndef BASIC_COMMS_MESSAGE_SIGNAL_MSGS_H
#define BASIC_COMMS_MESSAGE_SIGNAL_MSGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic_comms
{
template <class ContainerAllocator>
struct signal_msgs_
{
  typedef signal_msgs_<ContainerAllocator> Type;

  signal_msgs_()
    : time_x(0.0)
    , signal_y(0.0)  {
    }
  signal_msgs_(const ContainerAllocator& _alloc)
    : time_x(0.0)
    , signal_y(0.0)  {
  (void)_alloc;
    }



   typedef double _time_x_type;
  _time_x_type time_x;

   typedef float _signal_y_type;
  _signal_y_type signal_y;





  typedef boost::shared_ptr< ::basic_comms::signal_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic_comms::signal_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct signal_msgs_

typedef ::basic_comms::signal_msgs_<std::allocator<void> > signal_msgs;

typedef boost::shared_ptr< ::basic_comms::signal_msgs > signal_msgsPtr;
typedef boost::shared_ptr< ::basic_comms::signal_msgs const> signal_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic_comms::signal_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic_comms::signal_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::basic_comms::signal_msgs_<ContainerAllocator1> & lhs, const ::basic_comms::signal_msgs_<ContainerAllocator2> & rhs)
{
  return lhs.time_x == rhs.time_x &&
    lhs.signal_y == rhs.signal_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::basic_comms::signal_msgs_<ContainerAllocator1> & lhs, const ::basic_comms::signal_msgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace basic_comms

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::basic_comms::signal_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic_comms::signal_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_comms::signal_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_comms::signal_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_comms::signal_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_comms::signal_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic_comms::signal_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00f39935c5dcc9cf05628912678eba28";
  }

  static const char* value(const ::basic_comms::signal_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00f39935c5dcc9cfULL;
  static const uint64_t static_value2 = 0x05628912678eba28ULL;
};

template<class ContainerAllocator>
struct DataType< ::basic_comms::signal_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic_comms/signal_msgs";
  }

  static const char* value(const ::basic_comms::signal_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic_comms::signal_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time_x\n"
"float32 signal_y\n"
"\n"
;
  }

  static const char* value(const ::basic_comms::signal_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic_comms::signal_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_x);
      stream.next(m.signal_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signal_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic_comms::signal_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basic_comms::signal_msgs_<ContainerAllocator>& v)
  {
    s << indent << "time_x: ";
    Printer<double>::stream(s, indent + "  ", v.time_x);
    s << indent << "signal_y: ";
    Printer<float>::stream(s, indent + "  ", v.signal_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_COMMS_MESSAGE_SIGNAL_MSGS_H
